# from go-ethereum:
name: mac build and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos-amd64:
    name: build macos/amd64
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - name: Run tests
        run: go test -short ./...
        env:
          GOOS: darwin
          GOARCH: amd64

  build-macos-arm64:
    name: build macos/arm64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - name: Run tests
        run: go test -short ./...
        env:
          GOOS: darwin
          GOARCH: arm64
