# from go-ethereum:
name: windows build and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    services:
      artemis:
        image: apache/activemq-artemis:latest-alpine
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - name: Run unit tests
        run: go test -short ./...
        env:
          AMC_USER: artemis
          AMC_PASSWORD: artemis
