name: build develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      artemis:
        image: apache/activemq-artemis:latest-alpine
        ports:
          - 5672:5672
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.1
    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Get dependencies
      run: go mod download
    - name: Build
      run: go build -v .
    - name: Run unit tests
      run: go test -short ./...
    - name: Run integration tests
      run: ./run-tests.sh
