name: build develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - name: Check out code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
