# from go-ethereum:
name: mac build and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-amd64:
    name: build and test macos/amd64
    runs-on: macos-13
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.1
    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Get dependencies
      run: go mod download
    - name: Build
      run: go build -v -ldflags="-X 'github.com/makibytes/amc/cmd.version=${{ github.ref_name }}'" .
    - name: Run tests
      run: go test -short ./...

  macos-arm64:
    name: build and test macos/arm64
    runs-on: macos-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.1
    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Get dependencies
      run: go mod download
    - name: Build
      run: go build -v -ldflags="-X 'github.com/makibytes/amc/cmd.version=${{ github.ref_name }}'" .
    - name: Run tests
      run: go test -short ./...
