# from go-ethereum:
name: build and test linux/amd64

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ] # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      artemis:
        image: apache/activemq-artemis:latest-alpine
        ports:
          - 5672:5672
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - name: Check out code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      # - name: Run unit tests
      #   run: go test -short ./...
      #   env:
      #     AMC_USER: artemis
      #     AMC_PASSWORD: artemis
      # - name: Setup bats and bats libs
      #   uses: bats-core/bats-action@2.0.0
      # - name: Run integration tests
      #   run: bats
      #   env:
      #     AMC_USER: artemis
      #     AMC_PASSWORD: artemis
