name: build and release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build-and-release-all:
    name: Build and release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
        - goarch: arm64
          goos: windows
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Release
      uses: wangyoucao577/go-release-action@v1
      with:
        build_flags: "-tags=${{ matrix.goos }}"
        ldflags: "-X github.com/makibytes/amc/cmd.version=${{ github.ref_name }}"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: https://dl.google.com/go/go1.23.2.linux-amd64.tar.gz
        binary_name: amc
