# from go-ethereum:
name: build and test macos/amd64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
        env:
          GOOS: darwin
          GOARCH: amd64
      - name: Check out code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      # - name: Run tests
      #   run: go test -short ./...